// What every emitter needs from the schema (server/query/schema.js).

/** camelCase → snake_case (Python's field names). */
export const snake = (s) => s.replace(/[A-Z]/g, (c) => "_" + c.toLowerCase());

export const HEADER = "GENERATED by `npm run gen:query` (scripts/gen-query) from server/query/schema.js. Do not edit.";

/** The schema tables the runtimes read: per entity its fields (name, type, nullable) and query metadata. */
export function tables(schema, types) {
  const entities = {};
  for (const [name, e] of Object.entries(schema.entities)) {
    for (const spec of e.index) {
      for (const f of spec) if (e.fields.find((x) => x.name === f)?.type === "json") throw new Error(`${name}: json fields can't be indexed`);
    }
    entities[name] = {
      record: e.record, key: e.key, sortedBy: e.sortedBy ?? null, index: e.index, cells: e.cells, scopes: e.scopes,
      owner: e.owner ?? null, program: !!e.program,
      fields: e.fields.map((f) => ({ name: f.name, type: f.type, nullable: f.nullable })),
    };
  }
  const programs = Object.keys(entities).filter((k) => entities[k].program);
  if (programs.length !== 1) throw new Error("exactly one entity can be a program entity (HISTORY.<entity>)");
  return { types, entities, program: programs[0] };
}

/** One line of documentation, safe inside a comment. */
export const doc = (s) => String(s).replace(/\*\//g, "* /").replace(/\s+/g, " ").trim();
